name: Continuous integration

on:

  pull_request:
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'packages/*/tsconfig.json'
      - 'packages/*/tsconfig.*.json'
      - 'packages/*/test/**'
      - 'packages/*/api-extractor.json'
      - 'packages/*/test/examples/*/readme.md'
      - 'packages/*/.readme.md'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - 'eslint.config.*'
      - 'README.md'
      - '.github/workflows/ci.yml'
  push:
    paths:
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'packages/*/tsconfig.json'
      - 'packages/*/tsconfig.*.json'
      - 'packages/*/test/**'
      - 'packages/*/api-extractor.json'
      - 'packages/*/test/examples/*/readme.md'
      - 'packages/*/.readme.md'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - 'eslint.config.*'
      - 'README.md'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build:
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/compile-package.yml
    secrets: inherit

  lint:
    needs:
      - build
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    needs:
      - build
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: IT-Service-NPM/.github/.github/workflows/test-npm-package-pnpm.yml@main
    secrets: inherit

  npmJS:
    needs:
      - build
      - test
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      actions: read
      deployments: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm
          package-manager-cache: true
          cache-dependency-path: package.json, packages/*/package.json

      - uses: pnpm/action-setup@v4
        name: Install pnpm and packages
        with:
          run_install: true

      - name: Download packages 'dist'
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: packages/

      - name: Update API documentation
        run: pnpm run --if-present --recursive update-readme-API

      - name: Update readme.md
        run: pnpm run --if-present --recursive update-readme

      - uses: codfish/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
