---
name: Continuous integration

on:

  pull_request:
    branches:
      - main
    paths:
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'packages/*/tsconfig.json'
      - 'packages/*/tsconfig.*.json'
      - 'packages/*/test/**'
      - 'packages/*/api-extractor.json'
      - 'packages/*/test/examples/*/readme.md'
      - 'packages/*/.readme.md'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - 'eslint.config.*'
      - 'README.md'
      - '.github/workflows/ci.yml'
  push:
    paths:
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'packages/*/tsconfig.json'
      - 'packages/*/tsconfig.*.json'
      - 'packages/*/test/**'
      - 'packages/*/api-extractor.json'
      - 'packages/*/test/examples/*/readme.md'
      - 'packages/*/.readme.md'
      - 'tsconfig.json'
      - 'tsconfig.*.json'
      - 'eslint.config.*'
      - 'README.md'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build:
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/compile-package.yml
    secrets: inherit

  lint:
    needs:
      - build
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    needs:
      - build
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: IT-Service-NPM/.github/.github/workflows/test-npm-package-pnpm.yml@main
    secrets: inherit

  npmJS:
    needs:
      - build
      - test
    environment: npm
    runs-on: ubuntu-latest
    permissions:
      actions: read
      deployments: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: "IT-Service-NPM/.github/.github/actions/setup@main"

      - uses: "IT-Service-NPM/.github/.github/actions/download-packages-dist@main"

      - name: Update API documentation
        run: pnpm run --if-present --recursive build:readme:API

      - name: Update readme.md
        run: pnpm run --if-present --recursive build:readme

      - name: "Semantic Release"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "github-actions-shell"
          GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
          GIT_COMMITTER_NAME: "github-actions-shell"
          GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: "pnpm exec multi-semantic-release"
